### ISSUE TITLE
can create folder outside of the cloud directory + temp file don't delete

### ISSUE THREAD

**Issue by theo546** [zelon88/HRCloud2#14]
hi,
i found a bug, when you create a folder
put '../whatever' to create a folder outside the user directory

and i found an another bug, the temp file never got deleted
it's suposed to delete after 15 mins but it never delete,

and i found another thing, when i click on a file,
i must wait 3/4 seconds to get the download box(or music/video player)

(off-topic: can we use hrcloud without wordpress?
2: can we download file in bulk mode)

thanks for this amazing(and powerful) cloud system!

**Comment by theo546** [comment]
hello,
i found a way to increase performance, why not using symlink instead of copying the file?

**Comment by zelon88** [comment]
Hello! Thanks for pointing out the bugs and offering some suggestions!

> i found a bug, when you create a folder
put '../whatever' to create a folder outside the user directory

Fixed! This went a lot deeper than it seemed. Several Apps were affected as well. As far as I can tell this has been corrected. The leading dots and slashes should now be removed and the directory should go where it belongs.

> and i found an another bug, the temp file never got deleted
it's suposed to delete after 15 mins but it never delete,

Fixed! Janitor.php had some typo's, "index.html" was removed from the $defaultApps in appCore.php, and the AutoClean function was reworked a bit in cloudCore.php. Also somewhere along the line the temp file time-limit was changed to 1 hour. I have changed it back to 15 minutes.

> and i found another thing, when i click on a file,
i must wait 3/4 seconds to get the download box(or music/video player)

I reworked cloudCore.php's "download" function a bit to try and skip some logic. This won't really create a noticable increase in performance though.

I like your idea with symlinks. It's something I was actually not even aware of until you brought it up. Just a quick look through the PHP documentation makes it seem like this is a very plausible fix for slow-downloads. Feel free to send me some more ideas or even concept code to try out. I'm curious to see how much of the CloudTempDir we could eliminate. We may still need it on occasion for file conversions, but I'll have to play around with it some more.

> (off-topic: can we use hrcloud without wordpress?

It's possible, however the reason I included WordPress was to simplify the database connection and user-account creation portion of HRCloud2. If we can separate these functions from WordPress and strap them into HRC2 somehow WordPress would become unneeded. I'd like to separate, but I'm nervous about how arduos that task would be and what the backwards compatibility would look like. 

> 2: can we download file in bulk mode)

I think the simplest way to accomplish this would be to craft an Ajax call similar to the "convert" API input that will compress the selected files and return a prenamed archive. Then we could just hook this unique Ajax call to a button in the Drive section and users should be able to select their files, click the button, and download an archive.

**Comment by theo546** [comment]
@zelon88 Thanks for your answer 👍 
i modified the code to use Symlink, it seem to broke something, i will see (maybe) how to fix
(the auto clean system will use the date of the original file so it will delete the symlink, i used a fix to get the symlink date)

**Comment by theo546** [comment]
I attached the modified cloudCore.php
modified line: 141, 1132 to 1137, 1148
(yes the file is a txt file because github don't wan't PHP or ZIP file :/)
[cloudCore.txt](https://github.com/zelon88/HRCloud2/files/753450/cloudCore.txt)

**Comment by zelon88** [comment]
That's pretty good stuff. Seems to work great actually. I was concerned that if the file were cleaned before the user had completed the download that the upload woundn't complete. Using your code this proves to be false. I tried to make HRC2 stop a download in-progress by removing the link in-process. 

However, it seems that directories are still the old method on yours. This version has added line 128, modified line 141 and line 155 to also use symlinks on folder-contents (the intermediate folder is still created though, because the GUI needs it). 

It also appears as auto-clean still works fine, which is very cool. Unless you see and bugs that I'm missing feel free to submit as a push request and I'll roll it out asap.
[cloudCore.txt](https://github.com/zelon88/HRCloud2/files/753534/cloudCore.txt)

**Comment by theo546** [comment]
Bug found! Line 130 and 131, you writed '$file1 = $file' before $file was defined, i put the fix as attachment!
(by the way, maybe the sleep(1) in the code is not useful anymore, the symlink is instant!)
👍 
[cloudCore.txt](https://github.com/zelon88/HRCloud2/files/753551/cloudCore.txt)

**Comment by zelon88** [comment]
Hmm. $file is defined by the foreach on line127. I think we want $file1 before $file, but there are still bugs. This version seems to do the trick and is stable. 

The sleeps were for document conversions because in the beginning I had problems with Unoconv returning that it was complete but when PHP went looking for the file it would miss it. Early versions of HRC2 had a short-lived bug that sometimes required page refresh before converted documents showed up. 
I've deleted the sleeps and it seems document conversions still work fine. Maybe our dependencies fixed something? Either way, the sleeps are gone. ODF conversions don't seem to work though. Maybe I'll just remove support?

I also tried to set the auto clean time to 0 seconds, figuring HRC2 would pretty much clean up after itself in real-time. This worked for small files, but when I tried to download a 34MB .wav audio file I got an error and no file download. 5s still works though, curiously enough. Maybe a usleep will help?
[cloudCore.txt](https://github.com/zelon88/HRCloud2/files/753586/cloudCore.txt)
